version: '3'

services:
  catalogdb:
    container_name: catalogdb
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    restart: always
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
